import Foundation
import Observation
import os

private let logger = Logger(subsystem: "Torque-Soul-Media.TrickCam-APP-BUILT", category: "NewSession")

@Observable
final class NewSessionViewModel {
    struct AthleteDraft: Identifiable, Equatable {
        let id: UUID
        var name: String = ""
        var shortcode: String = ""
        var isShortcodeAutoGenerated: Bool = true
    }

    private let settingsStore: SettingsStore

    init(settingsStore: SettingsStore) {
        self.settingsStore = settingsStore
    }

    var sessionName: String = ""
    var athletes: [AthleteDraft] = []
    var errorMessage: String?
    var isShowingError = false

    // Athleten aus anderen Sessions, die heute (derselbe Kalendertag) bereits
    // angelegt wurden — ermöglicht mehrere Sessions für unterschiedliche
    // Spots am selben Tag, ohne dieselben Athleten erneut einzutippen
    // (Nutzerwunsch). Eine Session "schließt" dafür bewusst nicht vor dem
    // nächsten Kalendertag: Session.date ist unveränderlich (Models/Session.swift),
    // der reine Datumsvergleich in loadQuickAddCandidates() reicht deshalb für
    // den gesamten Tag aus, unabhängig davon, welche Session gerade aktiv ist.
    private(set) var quickAddCandidates: [Athlete] = []

    // Bereits im aktuellen Entwurf übernommene Kürzel verschwinden aus der
    // Auswahl, statt weiter antippbar zu bleiben.
    var availableQuickAddCandidates: [Athlete] {
        let usedShortcodes = Set(athletes.map { $0.shortcode.lowercased() })
        return quickAddCandidates.filter { !usedShortcodes.contains($0.shortcode.lowercased()) }
    }

    // Locale aus settingsStore.effectiveLocale statt Bundle.preferredLocalizations
    // (Bugfix, im Zuge der Sprachumschaltung gefunden) — folgt damit auch einer
    // erzwungenen App-Sprache (SettingsView "Sprache"), nicht nur der
    // iOS-Systemsprache, damit Datumsformat und angezeigte Textsprache nie
    // auseinanderlaufen.
    var today: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.locale = settingsStore.effectiveLocale
        return formatter.string(from: Date())
    }

    // Athletenliste darf leer bleiben (spec.md §8.2); das Kürzel ist die
    // Pflichtangabe pro Athlet, der Name ist optional — siehe hasShortcode-Filter.
    var canConfirm: Bool {
        let trimmedName = sessionName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedName.isEmpty else { return false }
        let eligible = athletes.filter(hasShortcode)
        let codes = eligible.map { $0.shortcode.lowercased() }
        return Set(codes).count == codes.count
    }

    @discardableResult
    func addAthlete() -> UUID {
        let draft = AthleteDraft(id: UUID())
        athletes.append(draft)
        return draft.id
    }

    func loadQuickAddCandidates(sessionStore: SessionStore) async {
        let today = SessionStore.currentDateString()
        let sessions: [Session]
        do {
            sessions = try await sessionStore.listSessions()
        } catch {
            // Nicht kritisch (reine Komfortfunktion, keine Datenveränderung) —
            // Session lässt sich weiterhin ganz normal per Hand anlegen, daher
            // kein Alert, nur Logging (CLAUDE.md §5.2).
            logger.error("Sessions für Athleten-Schnellauswahl konnten nicht geladen werden: \(error.localizedDescription)")
            return
        }
        var seenShortcodes = Set<String>()
        var candidates: [Athlete] = []
        for session in sessions where session.date == today {
            for athlete in session.athletes {
                let key = athlete.shortcode.lowercased()
                guard !seenShortcodes.contains(key) else { continue }
                seenShortcodes.insert(key)
                candidates.append(athlete)
            }
        }
        quickAddCandidates = candidates
    }

    // Übernimmt Name + Kürzel unverändert — isShortcodeAutoGenerated: false,
    // damit ein späteres Bearbeiten des Namens das bewusst übernommene Kürzel
    // nicht überschreibt (anders als bei einer frisch getippten Zeile).
    func quickAdd(_ athlete: Athlete) {
        let draft = AthleteDraft(id: UUID(), name: athlete.name, shortcode: athlete.shortcode, isShortcodeAutoGenerated: false)
        athletes.append(draft)
    }

    func removeAthlete(id: UUID) {
        athletes.removeAll { $0.id == id }
    }

    func nameChanged(forDraftId id: UUID, to newName: String) {
        guard let index = athletes.firstIndex(where: { $0.id == id }) else { return }
        athletes[index].name = newName
        // Solange der User das Kürzel nicht selbst angefasst hat, folgt es dem
        // Namen automatisch (spec.md §15.1.1).
        guard athletes[index].isShortcodeAutoGenerated else { return }
        let taken = Set(athletes.filter { $0.id != id }.map { $0.shortcode.lowercased() })
        athletes[index].shortcode = NameSanitizer.suggestShortcode(for: newName, avoiding: taken)
    }

    func shortcodeChanged(forDraftId id: UUID, to newValue: String) {
        guard let index = athletes.firstIndex(where: { $0.id == id }) else { return }
        athletes[index].shortcode = NameSanitizer.filterShortcodeInput(newValue)
        athletes[index].isShortcodeAutoGenerated = false
    }

    func shortcodeErrorMessage(forDraftId id: UUID) -> String? {
        guard let draft = athletes.first(where: { $0.id == id }), hasShortcode(draft) else { return nil }
        let collisionCount = athletes.filter {
            hasShortcode($0) && $0.shortcode.caseInsensitiveCompare(draft.shortcode) == .orderedSame
        }.count
        return collisionCount > 1 ? LocalizedStringResolver.string("Kürzel bereits vergeben", locale: settingsStore.effectiveLocale) : nil
    }

    func confirm(sessionStore: SessionStore) async -> Session? {
        let finalAthletes = athletes
            .filter(hasShortcode)
            .map {
                Athlete(
                    id: $0.id,
                    name: $0.name.trimmingCharacters(in: .whitespacesAndNewlines),
                    shortcode: $0.shortcode
                )
            }
        do {
            return try await sessionStore.createSession(name: sessionName, athletes: finalAthletes)
        } catch {
            let locale = settingsStore.effectiveLocale
            errorMessage = (error as? TrickCamError)?.userMessage(locale: locale) ?? LocalizedStringResolver.string("Die Session konnte nicht angelegt werden.", locale: locale)
            isShowingError = true
            return nil
        }
    }

    private func hasShortcode(_ draft: AthleteDraft) -> Bool {
        !draft.shortcode.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }
}
