import Foundation
import Observation

// Athleten-Verwaltung einer aktiven Session (spec.md §8.3/§11.2/§15.8) —
// wiederverwendet vom Athlet-Schnellzugriff auf dem Aufnahme-Bildschirm und
// vom Plus-Symbol in der Galerie. Ergänzen wirkt sofort, Entfernen ist
// gesperrt, solange dem Athleten bereits Clips zugeordnet sind.
@MainActor
@Observable
final class AthleteManagementViewModel {
    private let sessionId: UUID
    private let sessionStore: SessionStore
    private let settingsStore: SettingsStore

    private(set) var session: Session?

    var newName: String = ""
    var newShortcode: String = ""
    private var isShortcodeAutoGenerated = true

    var pendingRemoval: Athlete?
    var removalBlockedMessage: String?

    var errorMessage: String?
    var isShowingError = false

    init(sessionId: UUID, sessionStore: SessionStore, settingsStore: SettingsStore) {
        self.sessionId = sessionId
        self.sessionStore = sessionStore
        self.settingsStore = settingsStore
    }

    func load() async {
        do {
            session = try await sessionStore.session(withId: sessionId)
        } catch {
            present(error)
        }
    }

    func nameChanged(_ value: String) {
        newName = value
        guard isShortcodeAutoGenerated else { return }
        let taken = Set((session?.athletes ?? []).map { $0.shortcode.lowercased() })
        newShortcode = NameSanitizer.suggestShortcode(for: value, avoiding: taken)
    }

    func shortcodeChanged(_ value: String) {
        newShortcode = NameSanitizer.filterShortcodeInput(value)
        isShortcodeAutoGenerated = false
    }

    var shortcodeErrorMessage: String? {
        guard !newShortcode.isEmpty else { return nil }
        let collides = (session?.athletes ?? []).contains {
            $0.shortcode.caseInsensitiveCompare(newShortcode) == .orderedSame
        }
        return collides ? LocalizedStringResolver.string("Kürzel bereits vergeben", locale: settingsStore.effectiveLocale) : nil
    }

    var canAdd: Bool {
        !newShortcode.isEmpty && shortcodeErrorMessage == nil
    }

    func addAthlete() async {
        guard canAdd else { return }
        let athlete = Athlete(id: UUID(), name: newName.trimmingCharacters(in: .whitespacesAndNewlines), shortcode: newShortcode)
        do {
            session = try await sessionStore.addAthlete(athlete, toSessionId: sessionId)
            newName = ""
            newShortcode = ""
            isShortcodeAutoGenerated = true
        } catch {
            present(error)
        }
    }

    /// Athleten mit vorhandenen Clips lassen sich nicht direkt löschen —
    /// stattdessen ein erklärender Hinweis statt eines Bestätigungsdialogs
    /// (spec.md §15.8).
    func requestRemoval(_ athlete: Athlete) {
        let hasClips = session?.clips.contains { $0.athleteId == athlete.id } ?? false
        if hasClips {
            removalBlockedMessage = LocalizedStringResolver.string("„\(athlete.shortcode)“ hat bereits zugeordnete Clips. Verschiebe oder lösche sie zuerst in der Galerie, bevor der Athlet entfernt werden kann.", locale: settingsStore.effectiveLocale)
        } else {
            pendingRemoval = athlete
        }
    }

    func confirmRemoval() async {
        guard let athlete = pendingRemoval else { return }
        pendingRemoval = nil
        do {
            session = try await sessionStore.removeAthlete(id: athlete.id, fromSessionId: sessionId)
        } catch {
            present(error)
        }
    }

    private func present(_ error: Error) {
        let locale = settingsStore.effectiveLocale
        errorMessage = (error as? TrickCamError)?.userMessage(locale: locale) ?? LocalizedStringResolver.string("Ein unerwarteter Fehler ist aufgetreten.", locale: locale)
        isShowingError = true
    }
}
